---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.201
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.202
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.203
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.204
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.0.1
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.201
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.202
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.203
    ports:
      - port: 1
        protocol: TCP
  - addresses:
      - ip: 192.168.0.204
    ports:
      - port: 1
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
    - port: 1